In [1]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Loading the data
data = pd.read_csv('insurance.csv')
data.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [3]:
# Basic Checks
data.shape

(27, 2)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 560.0 bytes


In [5]:
data.bought_insurance.unique()

array([0, 1], dtype=int64)

In [6]:
data.describe()

age  bought_insurance
count  27.000000         27.000000
mean   39.666667          0.518519
std    15.745573          0.509175
min    18.000000          0.000000
25%    25.000000          0.000000
50%    45.000000          1.000000
75%    54.500000          1.000000
max    62.000000          1.000000

In [7]:
data.isnull().sum()

age                 0
bought_insurance    0
dtype: int64

In [8]:
# Define i/p and o/p variables
X = data[['age']]
y = data[['bought_insurance']]

In [9]:
# Splitting the data into training and testing
X_train,X_test,y_train,y_test = train_test_split(X,y)
X_train.shape

(20, 1)

In [10]:
X_test.shape

(7, 1)

In [11]:
#Define the model
model = LogisticRegression()
model

LogisticRegression()

In [12]:
# Training
model.fit(X_train,y_train)

E:\Users\ACER\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [13]:
# Prediction
y_predict = model.predict(X_test)
y_predict

array([0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [14]:
y_test

bought_insurance
12                 0
14                 1
25                 1
19                 0
3                  0
9                  1
11                 0

In [15]:
model.predict([[14]])

array([0], dtype=int64)

In [16]:
# Evaluation Metrics->accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_predict)

0.8571428571428571

In [17]:
confusion_matrix(y_test,y_predict)

array([[3, 1],
       [0, 3]], dtype=int64)

In [18]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.75      1.00      0.86         3

    accuracy                           0.86         7
   macro avg       0.88      0.88      0.86         7
weighted avg       0.89      0.86      0.86         7



In [19]:
#Logistic Regression=> Mt_cars.csv target=> am i/p select 4 best features