## Agenda
* Numpy introduction
* Array Creation->1D,2D,3D
* Attributes-> ndim,size,shape,dtype
* Functions-> arange,linspace,ravel,random,rand,resize
* Stacking->hstack,vstack
* Splitting-> hsplit,vsplit
* Matrix operations
* broadcasting, masking
* other functions-> eye,zeros,ones,max,min,copy,transpose,fliplr

### Numpy->Numerical Python
* homogeneous multidimensional collection of elements
* scientific and mathematical computations

#### Why use NumPy?

* NumPy arrays are faster and more compact than Python lists. 
* NumPy uses much less memory to store data 

In [1]:
import numpy as np

In [2]:
# 1D Data Creation
a1 = np.array([23,45,87,41,65])
a1

array([23, 45, 87, 41, 65])

In [3]:
#Attributes
print('Dimension',a1.ndim)
print('Size',a1.size) # no. of elements in the array
print('Shape',a1.shape) # no. of elements in the each dimension
print('DataType',a1.dtype)

Dimension 1
Size 5
Shape (5,)
DataType int32


In [6]:
# 2D Dimension Array Creation
a2 = np.array([[1,2,3,4],[2,5,1,7],[8,7,3,4]])
a2

array([[1, 2, 3, 4],
       [2, 5, 1, 7],
       [8, 7, 3, 4]])

In [7]:
type(a2)

numpy.ndarray

In [8]:
#Attributes
print('Dimension',a2.ndim)
print('Size',a2.size) # no. of elements in the array
print('Shape',a2.shape) # no. of elements in the each dimension
print('DataType',a2.dtype)

Dimension 2
Size 12
Shape (3, 4)
DataType int32


In [116]:
# Create an 2D array of shape 4,5
a3=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
a3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [10]:
#Attributes
print('Dimension',a3.ndim)
print('Size',a3.size) # no. of elements in the array
print('Shape',a3.shape) # no. of elements in the each dimension
print('DataType',a3.dtype)

Dimension 2
Size 20
Shape (4, 5)
DataType int32


In [117]:
a4 = np.array([[4,3,5],[1,2,3],[4,5,6],[7,5,4]])
a4

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [12]:
# 3D Array Creation
a5 = np.array([[[1,2,3],[4,7,5]],[[1,2,3],[4,7,5]],[[1,2,3],[4,7,5]]])
a5

array([[[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]]])

In [13]:
#Attributes
print('Dimension',a5.ndim)
print('Size',a5.size) # no. of elements in the array
print('Shape',a5.shape) # no. of elements in the each dimension
print('DataType',a5.dtype)

Dimension 3
Size 18
Shape (3, 2, 3)
DataType int32


#### Functions-> arange,linspace,ravel,reshape,random,rand

In [14]:
# arange->Return evenly spaced values within a given interval
np.arange(5) # stop(E)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(1,6) # start, stop(E)

array([1, 2, 3, 4, 5])

In [16]:
np.arange(1,11,2) #start, stop(E), step

array([1, 3, 5, 7, 9])

In [17]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [25]:
# linspace->Return evenly spaced numbers over a specified interval
np.linspace(1,100,15,retstep=True) # start,end(I),no.of elements

(array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
         29.28571429,  36.35714286,  43.42857143,  50.5       ,
         57.57142857,  64.64285714,  71.71428571,  78.78571429,
         85.85714286,  92.92857143, 100.        ]),
 7.071428571428571)

In [22]:
x.dtype

dtype('float64')

In [23]:
x=np.linspace(10,100,10,retstep=True)
x

(array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]), 10.0)

In [21]:
x.astype('int') # typecasting->cast to a specified type

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
# ravel-> array from any dimension yo 1D
a5

array([[[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]]])

In [28]:
a5.ravel()

array([1, 2, 3, 4, 7, 5, 1, 2, 3, 4, 7, 5, 1, 2, 3, 4, 7, 5])

In [29]:
a4.ravel()

array([4, 3, 5, 1, 2, 3, 4, 5, 6, 7, 5, 4])

In [31]:
#reshape
a4 # shape(4,3)

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [33]:
a4.reshape(2,6)

array([[4, 3, 5, 1, 2, 3],
       [4, 5, 6, 7, 5, 4]])

In [34]:
a4.reshape(3,4)

array([[4, 3, 5, 1],
       [2, 3, 4, 5],
       [6, 7, 5, 4]])

In [35]:
a4.reshape(2,2,3)

array([[[4, 3, 5],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 5, 4]]])

In [36]:
a4.reshape(2,3,2)

array([[[4, 3],
        [5, 1],
        [2, 3]],

       [[4, 5],
        [6, 7],
        [5, 4]]])

In [37]:
# random,rand,randint

In [42]:
# random-> Return random floats in the half-open interval [0.0, 1.0)
np.random.random(10)

array([0.37401459, 0.76235959, 0.38281384, 0.59867489, 0.52545714,
       0.77015523, 0.74757947, 0.73169012, 0.31677386, 0.06229184])

In [41]:
np.random.rand(5,4) # Random values in a given shape

array([[0.57303761, 0.52701932, 0.4755519 , 0.65454915],
       [0.07650179, 0.53355917, 0.93240479, 0.47885505],
       [0.62059372, 0.61705951, 0.68015459, 0.59752018],
       [0.68650276, 0.53245024, 0.59328443, 0.90664481],
       [0.67100764, 0.09798923, 0.25989503, 0.14172588]])

In [47]:
np.random.randint(1,10000,10)#Return random integers from `low` (inclusive) to `high` (exclusive) with no. of elements

array([3299,  655, 8946,  938, 6369, 8647, 7526, 8814, 3259, 8780])

In [48]:
a3 # 20 elements

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [52]:
#resize
x2=np.resize(a3,(5,5)) # resized with 25 elements
x2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5]])

In [51]:
x1 =np.resize(a3,(3,5))
x1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [57]:
x1[2][3]

6

In [59]:
x1[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [61]:
np.array(int(input("Enter values")))

Enter values5


array(5)

In [62]:
l1 = [1,2,3,4]
np.array(l1)

array([1, 2, 3, 4])

In [63]:
eval(input()) # evaluate function to evaluate an expression

5+6


11

### Stacking->hstack,vstack

In [64]:
a4

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [65]:
a3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [66]:
np.hstack((a3,a4)) #Stack arrays in sequence horizontally (column wise)

array([[1, 2, 3, 4, 5, 4, 3, 5],
       [2, 3, 4, 5, 6, 1, 2, 3],
       [3, 4, 5, 6, 7, 4, 5, 6],
       [4, 5, 6, 7, 8, 7, 5, 4]])

In [3]:
a7=a5.reshape(6,3)
a7

NameError: name 'a5' is not defined

In [72]:
np.vstack((a4,a7)) # Stack arrays in sequence vertically (row wise)

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4],
       [1, 2, 3],
       [4, 7, 5],
       [1, 2, 3],
       [4, 7, 5],
       [1, 2, 3],
       [4, 7, 5]])

### Splitting-> hsplit,vsplit

In [2]:
a7

NameError: name 'a7' is not defined

In [1]:
np.hsplit(a7,3)#Split an array into multiple sub-arrays horizontally (column-wise)

NameError: name 'np' is not defined

In [75]:
np.vsplit(a7,2) #Split an array into multiple sub-arrays vertically (row-wise)

[array([[1, 2, 3],
        [4, 7, 5],
        [1, 2, 3]]),
 array([[4, 7, 5],
        [1, 2, 3],
        [4, 7, 5]])]

In [78]:
np.vsplit(a7,3)

[array([[1, 2, 3],
        [4, 7, 5]]),
 array([[1, 2, 3],
        [4, 7, 5]]),
 array([[1, 2, 3],
        [4, 7, 5]])]

In [81]:
a8=a7.reshape(3,6)
a8

array([[1, 2, 3, 4, 7, 5],
       [1, 2, 3, 4, 7, 5],
       [1, 2, 3, 4, 7, 5]])

In [82]:
np.hsplit(a8,3)

[array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4],
        [3, 4]]),
 array([[7, 5],
        [7, 5],
        [7, 5]])]

In [83]:
np.hsplit(a8,2)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 7, 5],
        [4, 7, 5],
        [4, 7, 5]])]

### Matrix operations->#ADd,Sub,mul

In [4]:
# create 2 random arrays of shape (3,3), m1 and m2
m1 = (np.random.random(9).reshape(3,3)*10).astype('int')
m1

NameError: name 'np' is not defined

In [89]:
m2 = (np.random.random(9).reshape(3,3)*10).astype('int')
m2

array([[2, 3, 8],
       [9, 7, 7],
       [1, 0, 9]])

In [93]:
(np.random.random(9).reshape(3,3)*10).astype('int')

array([[4, 0, 7],
       [5, 6, 0],
       [6, 2, 4]])

In [96]:
(np.random.random(9).reshape(3,3)*10).astype('bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [98]:
m1

array([[8, 7, 3],
       [6, 2, 8],
       [9, 2, 1]])

In [99]:
m2

array([[2, 3, 8],
       [9, 7, 7],
       [1, 0, 9]])

In [97]:
np.add(m1,m2)

array([[10, 10, 11],
       [15,  9, 15],
       [10,  2, 10]])

In [100]:
np.subtract(m1,m2)

array([[ 6,  4, -5],
       [-3, -5,  1],
       [ 8,  2, -8]])

In [101]:
np.multiply(m1,m2)

array([[16, 21, 24],
       [54, 14, 56],
       [ 9,  0,  9]])

In [104]:
np.divide(m1,5)

array([[1.6, 1.4, 0.6],
       [1.2, 0.4, 1.6],
       [1.8, 0.4, 0.2]])

In [105]:
np.divmod(m1,7)

(array([[1, 1, 0],
        [0, 0, 1],
        [1, 0, 0]], dtype=int32),
 array([[1, 0, 3],
        [6, 2, 1],
        [2, 2, 1]], dtype=int32))

In [106]:
np.divide(m1,m2)

<ipython-input-106-ccc390e0dbb7>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(m1,m2)


array([[4.        , 2.33333333, 0.375     ],
       [0.66666667, 0.28571429, 1.14285714],
       [9.        ,        inf, 0.11111111]])

In [107]:
m3 = np.copy(m1)
m3

array([[8, 7, 3],
       [6, 2, 8],
       [9, 2, 1]])

In [118]:
# Broadcasting, Boolean Masking
a4

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [114]:
# Broadcasting
a4[:] = 100
a4

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [119]:
a3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [121]:
a3[:2] = 500
a3

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [  3,   4,   5,   6,   7],
       [  4,   5,   6,   7,   8]])

In [122]:
a4

array([[4, 3, 5],
       [1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [124]:
# Boolean Masking
a4 % 5 == 0

array([[False, False,  True],
       [False, False, False],
       [False,  True, False],
       [False,  True, False]])

In [125]:
a4 > 5 

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True, False, False]])

### other functions-> eye,zeros,ones,max,min,copy,transpose,fliplr

In [126]:
# eye-> Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [127]:
np.eye(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [128]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [129]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [130]:
a5

array([[[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]]])

In [131]:
np.max(a5)

7

In [132]:
np.min(a5)

1

In [133]:
a10=np.copy(a5)
a10

array([[[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]],

       [[1, 2, 3],
        [4, 7, 5]]])

In [136]:
a3

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [  3,   4,   5,   6,   7],
       [  4,   5,   6,   7,   8]])

In [135]:
np.transpose(a3)

array([[500, 500,   3,   4],
       [500, 500,   4,   5],
       [500, 500,   5,   6],
       [500, 500,   6,   7],
       [500, 500,   7,   8]])

In [137]:
np.fliplr(a3)

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [  7,   6,   5,   4,   3],
       [  8,   7,   6,   5,   4]])

In [138]:
np.flipud(a3)

array([[  4,   5,   6,   7,   8],
       [  3,   4,   5,   6,   7],
       [500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500]])

In [139]:
np.flip(a3)

array([[  8,   7,   6,   5,   4],
       [  7,   6,   5,   4,   3],
       [500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500]])

In [140]:
a3

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [  3,   4,   5,   6,   7],
       [  4,   5,   6,   7,   8]])