### Agenda
* Data Structures-Series, Dataframe
* Series-Creation,Attributes,Methods
* DataFrame-Creation,Attributes,Methods
* Indexing and Selction

## Pandas-> panel data
* powerful open source tool for data analysis and manipulation

### Series
* single col,multiple rows

In [7]:
import numpy as np

In [8]:
np.random.rand(6,4,5,2,1,2,1,2,1,2)

array([[[[[[[[[[0.03898952, 0.90241124]],

              [[0.34947853, 0.85792957]]]],



            [[[[0.54255057, 0.32971541]],

              [[0.47170323, 0.14069947]]]]]],





          [[[[[[0.47663289, 0.01908373]],

              [[0.25373835, 0.45947801]]]],



            [[[[0.34717969, 0.95049156]],

              [[0.199795  , 0.31122675]]]]]]],






         [[[[[[[0.36953067, 0.72812189]],

              [[0.37041797, 0.92758741]]]],



            [[[[0.23872985, 0.06138613]],

              [[0.57468138, 0.85863773]]]]]],





          [[[[[[0.13429776, 0.11978248]],

              [[0.55931412, 0.27638539]]]],



            [[[[0.72879158, 0.85751502]],

              [[0.85687129, 0.98746026]]]]]]],






         [[[[[[[0.41058483, 0.01577211]],

              [[0.12595133, 0.93566765]]]],



            [[[[0.48445299, 0.28289487]],

              [[0.45629719, 0.33673369]]]]]],





          [[[[[[0.73113964, 0.30830724]],

              [[0.53363185, 0.271

In [9]:
import pandas as pd

In [10]:
# Series creation
s1 = pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
type(s1)

pandas.core.series.Series

In [12]:
s1.index = ['R1','R2','R3','R4']
s1

R1    1
R2    2
R3    3
R4    4
dtype: int64

In [13]:
print(s1.dtype)
print(s1.ndim)
print(s1.size)
print(s1.shape)

int64
1
4
(4,)


In [14]:
s1['R1']

1

In [15]:
s1['R4']

4

In [16]:
s1[0:3]

R1    1
R2    2
R3    3
dtype: int64

In [17]:
s1[::2]

R1    1
R3    3
dtype: int64

# DataFrame
* multiple rows and columns
* similar to Excel

In [18]:
# DataFrame Creation->values, arrays, random nos., list, tuples, dict
df1 = pd.DataFrame([[1,2,3,6],[5,6,7,9],[4,2,8,1]])
df1

0  1  2  3
0  1  2  3  6
1  5  6  7  9
2  4  2  8  1

In [19]:
# Assigning names to rows & columns
df1.index = ['R1', 'R2', 'R3']
df1.columns = ['C1','C2' ,'C3', 'C4']
df1

C1  C2  C3  C4
R1   1   2   3   6
R2   5   6   7   9
R3   4   2   8   1

In [20]:
df1.index = 'R11 R22 R33'.split()
df1.columns = 'C11 C22 C33 C44'.split()
df1

C11  C22  C33  C44
R11    1    2    3    6
R22    5    6    7    9
R33    4    2    8    1

In [21]:
# Create DF with arrays
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6]]))
df2

0  1  2
0  1  2  3
1  4  5  6

In [22]:
# Create DF with random nos, list and tuple (2,3)
df3 = pd.DataFrame(np.random.randint(1,1000,6).reshape(2,3))
df3

0    1    2
0  672   44  854
1  210  409  529

In [23]:
df4 = pd.DataFrame(np.random.randint(1,2000,15).reshape(5,3))
df4

0     1     2
0  1932  1879   978
1   871  1660   160
2   234  1877   152
3   708   294    93
4  1388   941  1060

In [24]:
df5 = pd.DataFrame([[1,4,5,6,7],[2,3,6,4,9]])
df5

0  1  2  3  4
0  1  4  5  6  7
1  2  3  6  4  9

In [25]:
df6 = pd.DataFrame(((1,4,5,6,7),(2,3,6,4,9)))
df6

0  1  2  3  4
0  1  4  5  6  7
1  2  3  6  4  9

In [26]:
d1 = {'Names':['Deepa','Nithu','Shashu'],'Age':[33,3,6]}
d1

{'Names': ['Deepa', 'Nithu', 'Shashu'], 'Age': [33, 3, 6]}

In [27]:
df7 = pd.DataFrame(d1)
df7

Names  Age
0   Deepa   33
1   Nithu    3
2  Shashu    6

In [28]:
# Create DF with shape 5,6 with any values and give names to rows & cols
df8 = pd.DataFrame(data=np.random.randint(1,2000,30).reshape(5,6),index='R1 R2 R3 R4 R5'.split(),columns='A B C D E G'.split())
df8

A     B     C     D     E     G
R1  1358  1453   210   288  1927   545
R2  1180  1463   793   233   250  1335
R3  1750   261  1974   298   167   863
R4  1741   754  1698  1395  1069   839
R5    76    14  1881   559   193  1300

In [29]:
#Attributes-> values,index,columns,ndim,size,shape
print(df8.ndim)
print(df8.size)
print(df8.shape)
print(df8.index)
print(df8.columns)
print(df8.values)

2
30
(5, 6)
Index(['R1', 'R2', 'R3', 'R4', 'R5'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'G'], dtype='object')
[[1358 1453  210  288 1927  545]
 [1180 1463  793  233  250 1335]
 [1750  261 1974  298  167  863]
 [1741  754 1698 1395 1069  839]
 [  76   14 1881  559  193 1300]]


In [30]:
df8

A     B     C     D     E     G
R1  1358  1453   210   288  1927   545
R2  1180  1463   793   233   250  1335
R3  1750   261  1974   298   167   863
R4  1741   754  1698  1395  1069   839
R5    76    14  1881   559   193  1300

In [31]:
# Indexing and slicing-> iloc,loc and conditions
#iloc-> index based location
df8.iloc[1:5,1:3]

B     C
R2  1463   793
R3   261  1974
R4   754  1698
R5    14  1881

In [32]:
# loc-> location(names of col & rows)
df8.loc[:,['A','C','E']]

A     C     E
R1  1358   210  1927
R2  1180   793   250
R3  1750  1974   167
R4  1741  1698  1069
R5    76  1881   193

In [33]:
df8.loc[['R1','R3'],['A','C','E']]

A     C     E
R1  1358   210  1927
R3  1750  1974   167

In [34]:
#condition based retrievel
df8[df8>1000]

A       B       C       D       E       G
R1  1358.0  1453.0     NaN     NaN  1927.0     NaN
R2  1180.0  1463.0     NaN     NaN     NaN  1335.0
R3  1750.0     NaN  1974.0     NaN     NaN     NaN
R4  1741.0     NaN  1698.0  1395.0  1069.0     NaN
R5     NaN     NaN  1881.0     NaN     NaN  1300.0

In [35]:
df8>1000

A      B      C      D      E      G
R1   True   True  False  False   True  False
R2   True   True  False  False  False   True
R3   True  False   True  False  False  False
R4   True  False   True   True   True  False
R5  False  False   True  False  False   True

In [36]:
#Reading the dataset
data = pd.read_csv('mtcars.csv')
data

FileNotFoundError: [Errno 2] No such file or directory: 'mtcars.csv'

In [ ]:
type(data)

In [ ]:
# Methods-> head(), tail(),info(),describe(),unique() 
data.head() # displays first 5 records

In [ ]:
data.tail() # displays last 5 records

In [ ]:
data.shape

In [ ]:
data.info() # basic info(datatypes)

In [ ]:
data.describe() # statistical info of values

In [37]:
data.describe(include='object')

NameError: name 'data' is not defined

In [38]:
data.am.unique()

NameError: name 'data' is not defined

In [39]:
data.gear.unique()

NameError: name 'data' is not defined